In [11]:
import pandas as pd

In [20]:
s = pd.Series([1,2,3,4,5,6], index = ['a','b','c','d','e','f'])

In [21]:
s

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [22]:
df = pd.DataFrame({"names" : ['Ana','Ryan','Ben'], "marks": [78,65,92]})

In [23]:
df

  names  marks
0   Ana     78
1  Ryan     65
2   Ben     92

In [29]:
df = pd.read_csv("IRIS.csv")

In [30]:
df

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [32]:
df.tail()

     sepal_length  sepal_width  petal_length  petal_width         species
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [33]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [34]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB

In [39]:
df[["sepal_length",'sepal_width']]

     sepal_length  sepal_width
0             5.1          3.5
1             4.9          3.0
2             4.7          3.2
3             4.6          3.1
4             5.0          3.6
..            ...          ...
145           6.7          3.0
146           6.3          2.5
147           6.5          3.0
148           6.2          3.4
149           5.9          3.0

[150 rows x 2 columns]

In [40]:
df.iloc[0]

sepal_length            5.1
sepal_width             3.5
petal_length            1.4
petal_width             0.2
species         Iris-setosa
Name: 0, dtype: object

In [42]:
df.rename(columns={"sepal_length":"SL"})

      SL  sepal_width  petal_length  petal_width         species
0    5.1          3.5           1.4          0.2     Iris-setosa
1    4.9          3.0           1.4          0.2     Iris-setosa
2    4.7          3.2           1.3          0.2     Iris-setosa
3    4.6          3.1           1.5          0.2     Iris-setosa
4    5.0          3.6           1.4          0.2     Iris-setosa
..   ...          ...           ...          ...             ...
145  6.7          3.0           5.2          2.3  Iris-virginica
146  6.3          2.5           5.0          1.9  Iris-virginica
147  6.5          3.0           5.2          2.0  Iris-virginica
148  6.2          3.4           5.4          2.3  Iris-virginica
149  5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [46]:
df['sepal_length'] = df['sepal_length'].astype(int)

In [48]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    int64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    str
dtypes: float64(3), int64(1), str(1)
memory usage: 6.0 KB

In [49]:
df["sepal_length"][0]

np.int64(5)

In [50]:
df["zeros"] = [0 for i in range(len(df))]

In [51]:
df

,sepal_length,sepal_width,petal_length,petal_width,species,zeros
0,5,3.5,1.4,0.2,Iris-setosa,0
1,4,3.0,1.4,0.2,Iris-setosa,0
2,4,3.2,1.3,0.2,Iris-setosa,0
3,4,3.1,1.5,0.2,Iris-setosa,0
4,5,3.6,1.4,0.2,Iris-setosa,0
...,...,...,...,...,...,...
145,6,3.0,5.2,2.3,Iris-virginica,0
146,6,2.5,5.0,1.9,Iris-virginica,0
147,6,3.0,5.2,2.0,Iris-virginica,0
148,6,3.4,5.4,2.3,Iris-virginica,0
149,5,3.0,5.1,1.8,Iris-virginica,0

In [53]:
def fx(a):
    return a+1
df["zeros + 1"] = df["zeros"].apply(fx)

In [54]:
df

,sepal_length,sepal_width,petal_length,petal_width,species,zeros,zeros + 1
0,5,3.5,1.4,0.2,Iris-setosa,0,1
1,4,3.0,1.4,0.2,Iris-setosa,0,1
2,4,3.2,1.3,0.2,Iris-setosa,0,1
3,4,3.1,1.5,0.2,Iris-setosa,0,1
4,5,3.6,1.4,0.2,Iris-setosa,0,1
...,...,...,...,...,...,...,...
145,6,3.0,5.2,2.3,Iris-virginica,0,1
146,6,2.5,5.0,1.9,Iris-virginica,0,1
147,6,3.0,5.2,2.0,Iris-virginica,0,1
148,6,3.4,5.4,2.3,Iris-virginica,0,1
149,5,3.0,5.1,1.8,Iris-virginica,0,1

In [56]:
df.to_csv("export.csv")

In [70]:
df1 = pd.DataFrame({"names" : ['Ana','Ryan','Ben'], "marks": [78,65,92]})

In [71]:
df1

  names  marks
0   Ana     78
1  Ryan     65
2   Ben     92

In [73]:
df2 = pd.DataFrame({"names" : ['Aryan','Ron','Benedict'], "marks": [75,66,94]})

In [74]:
df2

      names  marks
0     Aryan     75
1       Ron     66
2  Benedict     94

In [75]:
pd.merge(df1,df2, on="marks")

Empty DataFrame
Columns: [names_x, marks, names_y]
Index: []